services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/awards
      - JWT_SECRET=devsecret
      - JIRA_EMAIL=myidprasannas@gmail.com
      - JIRA_API_TOKEN=ATATT3xFfGF0qFr3O85a1dL3Yb3dKSK_HufpnIuKt4G-J5Bd6aqoCOdZuuozqSakrC3O6QeevvI4umLsr9Igt9RHQAeAmChMBeVCTAMmcdghfcIBJaw_swBUNP7eQJDe-d4xUVb3vEZSXl0ujICyFei9pDlgCCW85bvaJCF94z4Ru87N1d98lqI=FDFC3BF3
      - JIRA_DOMAIN=harshal782002.atlassian.net
      - PROJECT_KEY=SCRUM
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awards
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - api

volumes:
  pgdata:
