"""Change nominee_id to String

Revision ID: 3b0fa418ab04
Revises: dbae5adf33ee
Create Date: 2025-08-17 17:37:04.013801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b0fa418ab04'
down_revision: Union[str, Sequence[str], None] = 'dbae5adf33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nominations', 'nominee_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('nominations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nominations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'nominations', 'employees', ['nominee_id'], ['id'])
    op.create_foreign_key(None, 'nominations', 'users', ['manager_id'], ['id'])
    op.alter_column('password_resets', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('password_resets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'password_resets', 'users', ['user_id'], ['id'])
    op.add_column('sentiment_results', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('sentiment_results', 'nomination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sentiment_results', 'employee_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('sentiment_results', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'sentiment_results', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'sentiment_results', 'nominations', ['nomination_id'], ['id'])
    op.create_foreign_key(None, 'sentiment_results', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentiment_results', type_='foreignkey')
    op.drop_constraint(None, 'sentiment_results', type_='foreignkey')
    op.drop_constraint(None, 'sentiment_results', type_='foreignkey')
    op.alter_column('sentiment_results', 'analyzed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sentiment_results', 'employee_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sentiment_results', 'nomination_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sentiment_results', 'id')
    op.drop_constraint(None, 'password_resets', type_='foreignkey')
    op.alter_column('password_resets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_resets', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'nominations', type_='foreignkey')
    op.drop_constraint(None, 'nominations', type_='foreignkey')
    op.alter_column('nominations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('nominations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nominations', 'nominee_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
