"""Add is_approved and timestamps to employees

Revision ID: dbae5adf33ee
Revises: 4ebe7bbccbec
Create Date: 2025-08-17 10:30:56.539147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbae5adf33ee'
down_revision: Union[str, Sequence[str], None] = '4ebe7bbccbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employees', 'id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
